### ISSUE TITLE
Chart title should be passed as data 

### ISSUE THREAD

**Issue by austinrutledge0** [d3-node/d3node-barchart#10]
User should be able to pass custom chart title.

**Comment by sievins** [comment]
I've just started using this library and found a round about way of doing this.

```javascript
const d3nBar = require('d3node-barchart')
const data = require('./your-data')

const title = 'My awesome chart'
const container = `
  <div id="container">
    <h2>${title}</h2>
    <div id="chart"></div>
  </div>
`

d3nBar({ data, container })
```

**Comment by geekplux** [comment]
Thank @sievins for providing a solution. 
@austinrutledge0  https://github.com/d3-node/d3node-barchart/blob/master/index.js#L8 exclude the title from container, join it after passed custom title

**Comment by geekplux** [comment]
And https://github.com/sievins/record-wifi-speed/pull/9 have solved this issue, thanks
